import React from "react";

/**
 * Generates a Table of Contents (TOC) from HTML content and returns
 * the modified HTML string with the embedded TOC.
 *
 * @param contentHtml - The HTML string to scan for headings (h2–h6).
 * @param positionAfter - Zero-based paragraph index after which to insert
 *   the TOC. Use -1 to prepend before all content. Defaults to 0
 *   (after the first paragraph).
 * @param icon - Custom toggle icon: an SVG string or an image URL.
 *   Defaults to a built-in chevron SVG.
 * @returns The modified HTML string with the embedded TOC.
 */
export declare function generateToc(
  contentHtml: string,
  positionAfter?: number,
  icon?: string | null
): string;

/**
 * React component that renders HTML content (including an embedded TOC
 * generated by generateToc) and wires up the collapsible toggle behaviour.
 */
export declare const TocWrapper: React.FC<{ html: string }>;
