"use client";

import React, { useEffect, useRef } from "react";

/**
 * Renders HTML content (including an embedded TOC generated by generateToc)
 * and wires up the collapsible toggle behaviour.
 *
 * @param {{ html: string }} props
 */
export const TocWrapper = ({ html }) => {
  // Fix #9: Use a ref to scope DOM queries to THIS wrapper's subtree.
  // This means multiple <TocWrapper> instances on the same page each
  // control their own toggle independently.
  const wrapperRef = useRef(null);

  // Fix #10: Include `html` in the dependency array so the effect re-runs
  // (and re-attaches the listener) whenever the content changes.
  useEffect(() => {
    const container = wrapperRef.current;
    if (!container) return;

    const btn = container.querySelector(".rtb-toggle-btn");
    const list = container.querySelector(".rtb-toc-list");
    if (!btn || !list) return;

    const toggle = () => {
      const isVisible = list.style.display === "block";
      list.style.display = isVisible ? "none" : "block";
      btn.classList.toggle("rtb-open", !isVisible);
    };

    btn.addEventListener("click", toggle);
    return () => btn.removeEventListener("click", toggle);
  }, [html]); // re-attach when html prop changes

  return (
    <div
      ref={wrapperRef}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
};

export default TocWrapper;